" leader is a comma now
let mapleader = ','
let g:ackprg = "ag"


" C-?? mapping depending on the mode(s)
" Insert: C-O execute a command and return to insert mode

" Use pathogen to easily modify the runtime path to include all
" " plugins under the ~/.vim/bundle directory
filetype off
call pathogen#infect()
filetype plugin indent on

syntax on

" Some plugin seems to search for something at startup, so this fixes that.
silent! nohlsearch

" ----------------------------------------------------------------------------
" CUSTOM COMMANDS
" ----------------------------------------------------------------------------
" NB: command! force the command to be redefined if it exist
" I always hit ":W" instead of ":w" because I linger on the shift key...
command! Q q
command! W w

" Close all buffers except this one
command! BufCloseOthers %bd|e#

command! ProseMode call ProseMode()
" Codex commands:
"   :Codex
"   :Codex explain this module
"   :'<,'>CodexSelection add tests for this function
command! -nargs=* Codex call CodexOpen(<q-args>)
command! -range -nargs=* CodexSelection call CodexSendSelection(<q-args>)

command! -bang -nargs=* GGrep    call GGrep('<bang>', [<f-args>])
" To be used only for finding something
command! -bang -nargs=* GGrepw   call GGrepwrapper('<bang>', [<f-args>])
command! -bang VGGrep            call VGGrepfunc('<bang>')
" argument to VAckfunc will be grep or grep! depending how Vack is called
command! -bang VAck              call VAckfunc('grep<bang>')
command! -bang -nargs=* -complete=file Sack           call Sackfunc('grep<bang>', <q-args>)

""" Autocommands
augroup config

autocmd BufEnter *.md setlocal textwidth=0 | setlocal swapfile | setlocal shortmess-=A
" Resize panes when window/terminal gets resize
autocmd VimResized * :wincmd =

" Fix annoyances in the QuickFix window, like scrolling too much
autocmd FileType qf setlocal number nolist
autocmd Filetype qf wincmd J " Makes sure it's at the bottom of the vim window

" Some quick debugging
autocmd BufEnter *.py iabbr pou print('pouet
autocmd BufEnter *.py iabbr tata print('tatayoyo
autocmd BufEnter *.sh iabbr pou echo 'pouet
autocmd BufEnter *.sh iabbr tata echo 'tatayoyo
autocmd FileType sh iabbr pou echo 'pouet
autocmd FileType sh iabbr tata echo 'tatayoyo

" No more than 80c long red thing for pdf
if exists('+colorcolumn')
  autocmd BufReadPre *.pdf setlocal colorcolumn=0
endif

" Allow pdf to be opened in Vim
autocmd BufReadPre *.pdf setlocal ro nowrap
autocmd BufReadPre *.pdf setlocal noruler
autocmd BufRead *.pdf silent %!pdftotext "%" -nopgbrk -layout -q -eol unix -
autocmd BufReadPost *.pdf exec "%s/[^[:alnum:][:punct:][:space:]]//g"

" By default vim keep in the mark named " the last line where the cursor was
" when the file was last open.
" '" is how to get this address, of course we need to escape this when calling functions like line()
" or execute so "'\""
" Note ' or ` is the same, and using g' over just ' means that the jump list is not changed
" So with the autocmd if the mark " is set then go to this mark: g'" but
" but because this part of an exe we need to escape it
" It's basically to allow to go back to the last position in the file when
" the file has been read
autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal g`\"" |
        \ endif
autocmd BufWinEnter COMMIT_EDITMSG,*.diff,*.patch,*.patches.txt call CommitMessages()

au BufNewFile,BufRead *.sls,Saltfile call FallbackSalt()
au BufNewFile,BufRead *.dockerfile set filetype=dockerfile

augroup END

" ----------------------------------------------------------------------------
" OPTIONS
" ----------------------------------------------------------------------------
" control where we store marks 
"set viminfofile='$HOME/.viminfo'
" 20 marks and 100 registers
"set viminfo='20,\"100
"set smarttab               " insert tabs on the start of a line according to
                            " shifwidth, not tabstop
set autoindent              " Carry over indenting from previous line
set backspace=indent,eol,start
                            " Allow backspace beyond insertion point
set cindent                 " Automatic program indenting
set cinkeys-=0#             " Comments don't fiddle with indenting
set cino=                   " See :h cinoptions-values
set clipboard=unnamedplus
set commentstring=\ \ #%s   " When folds are created, add them to this
set copyindent              " Make autoindent use the same chars as prev line
set directory-=.            " Don't store temp files in cwd, ie. take what you have already in
                            " directory variable and remove '.' from it
set encoding=utf8           " UTF-8 by default
set expandtab               " No tabs
set fileformats=unix,dos,mac  " Prefer Unix
set fillchars=vert:\ ,stl:\ ,stlnc:\ ,fold:-,diff:┄
                            " Unicode chars for diffs/folds, and rely on
                            " Colors for window borders
silent! set foldmethod=marker " Use braces by default
set formatoptions=tcqn1     " t - autowrap normal text
                            " c - autowrap comments
                            " q - gq formats comments
                            " n - autowrap lists
                            " 1 - break _before_ single-letter words
                            " 2 - use indenting from 2nd line of para
set hidden                  " Don't prompt to save hidden windows until exit
set history=200             " How many lines of history to save
set hlsearch                " Hilight searching
set ignorecase              " Case insensitive
set incsearch               " Search as you type
set infercase               " Completion recognizes capitalization
set laststatus=2            " Always show the status bar
set linebreak               " Break long lines by word, not char
set list                    " Show whitespace as special chars - see listchars
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:· " Unicode characters for various things
set matchtime=2             " Tenths of second to hilight matching paren
set nomodeline              " teh hackerz!!!1
silent! set mouse=a         " Use the mouse
set nobackup                " No backups left after done editing
set visualbell t_vb=        " No flashing or beeping at all
set nowritebackup           " No backups made while editing
set printoptions=paper:letter " US paper
set ruler                   " Show row/col and percentage
set scroll=4                " Number of lines to scroll with ^U/^D
set scrolloff=15            " Keep cursor away from this many chars top/bot
set sessionoptions-=options " Don't save runtimepath in Vim session (see tpope/vim-pathogen docs)
set shiftround              " Shift to certain columns, not just n spaces
set shiftwidth=2            " Number of spaces to shift for autoindent or >,<
set shortmess+=A            " Don't bother me when a swapfile exists
set showbreak=              " Show for lines that have been wrapped, like Emacs
set showmatch               " Hilight matching braces/parens/etc.
set sidescrolloff=3         " Keep cursor away from this many chars left/right
set smartcase               " Lets you search for ALL CAPS
set softtabstop=2           " Spaces 'feel' like tabs
set suffixes+=.pyc          " Ignore these files when tab-completing
set tabstop=2               " The One True Tab
set textwidth=100           " 100 is the new 80
set thesaurus+=~/.vim/mthes10/mthesaur.txt
set wildmenu                " Show possible completions on command line
set wildmode=list:longest,full " List all options and complete
set wildignore=*.class,*.o,*~,*.pyc,*.class,*.swp,*.bak,.git,node_modules  " Ignore certain files in tab-completion

set pastetoggle=<F2>        " Allow to switch in paste mode
set undolevels=1000         " use many muchos levels of undo
set title                   " change the terminal's title
set tags=./tags,./TAGS,tags,TAGS

"There is no point of doing noswapfile with shortmess+=A because if there is a swapfile (ie.
".foo.swp) vim will ignore it and right away create .foo.swo. So it's kind of the same but in case
"there is still a swapfile if really needed
"Something to note: polyglote plugin is changing directory to contain $HOME/.vim// and shortmess to
"have also +A

set statusline=
set statusline+=%<                 " set truncation point everything else is shown even if we
                                    " don't have enough space
set statusline+=%f%m%r             " full path + modification marker (%m) + mode (%r)
set statusline+=%11(buffer:%.4n%)  " buffer number, make everything fit in 11 chars
                                    " start abreviating buffers that have
                                    " more than 4 digits (>1000)
set statusline+=\ %#warningmsg#    " Set highlight group %#...# called warninmsg
" As of 2023 don't use Syntastic anymore but ALE so there is no point to use it
"set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*\                " %* bringrs the highlighting to what was before

set statusline+=%15(L%l,C%c%V%)\  " %15( is the width specification, ends with %)
                                  " Line and Column and Virtual column
set statusline+=%3P               " Add position in the buffer (top, All or pct)

" Things like vim-polyglot are messing up with this when they are forcing the colors
" to be 16 if you had 8, so let's go ahead and force it before vim-polyglot is doing it.
" It will avoid having the ctermbg being changed, also let's go big and set it to 256 colors
set t_Co=256
set background=dark
" No matter what the documentation says the effect of noinsert is to highlight what deoplete put
" first so that pressing return would just complete
set completeopt=menu,noinsert

colors slate

" Make status line clearer when vsplit is used
hi StatusLine  ctermbg=5 cterm=bold

" The yellowish stuff is not great
hi Comment ctermfg=LightGreen

" Dark blue better that light blue ?
hi Search ctermbg=darkblue

" LSC is aliasing lscDiagnosticWarning to SpellBad by default it's a red background that make
" things very hard to read
" Maybe 10 ?
hi SpellBad ctermbg=10 term=bold

" Colors
" Maybe this one
highlight Pmenu ctermbg=darkblue guibg=darkblue
" graybg is hard to read when doing hover
"highlight Pmenu ctermbg=gray guibg=gray
highlight PmenuSel ctermbg=Magenta guibg=Magenta ctermfg=black guibg=black

" Pmenu – normal item
" PmenuSel – selected item
" PmenuSbar – scrollbar
" PmenuThumb – thumb of the scrollbar


" This needs to be at the and obviously
" Now load specifics to this host
" Specify the path to `coverage.json` file relative to your current working directory.
let g:coverage_json_report_path = 'coverage/coverage-final.json'

" Define the symbol display for covered lines
let g:coverage_sign_covered = '⦿'
" Define the interval time of updating the coverage lines
let g:coverage_interval = 5000

" Do not display signs on covered lines
let g:coverage_show_covered = 0

" Display signs on uncovered lines
let g:coverage_show_uncovered = 1

" 300 ms for completion
let g:ale_completion_delay = 300
let g:copilot_idle_delay = 400

let g:ale_disable_lsp = 0

let s:config_root = expand('<sfile>:p:h') . '/.vimrc.d'
" In the repo the path is vimrc but onced installed it will be ~/.vimrc.d
for s:file in [
      \ '20-mappings.vim',
      \ '30-functions.vim',
      \ '40-lsp.vim',
      \ ]
  execute 'source' fnameescape(s:config_root . '/' . s:file)
endfor

unlet s:file
unlet s:config_root

" TMUX config
" let's make this optional if tmux is not installed
if executable('tmux') && exists('$TMUX')
  if v:version >= 900
    def DisableTmuxMouse()
      job_start(['tmux', 'setw', '-g', 'mouse', 'off'])
    enddef

    def EnableTmuxMouse()
      job_start(['tmux', 'setw', '-g', 'mouse', 'on'])
    enddef
    augroup TmuxMouseToggle
      autocmd!
      autocmd VimEnter * call DisableTmuxMouse()
      autocmd VimLeavePre * call EnableTmuxMouse()
    augroup END
  else
    command! DisableTmuxMouse silent !tmux setw -g mouse off
    command! EnableTmuxMouse silent !tmux setw -g mouse on

    augroup TmuxMouseToggle
        autocmd!
        autocmd VimEnter * silent !tmux setw -g mouse off
        autocmd VimLeave * silent !tmux setw -g mouse on
    augroup END
  endif
endif

if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
